### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by devfresher** [FreeOps-Tools/api#20]
### What would you like to share?

Giving the codebase a proper structure. 

The API is only written in an index.js file, which looks jam-packed and can be difficult to work on new features as time goes on. The project can be made simplified into different modules while also considering "separation of concerns" and following best practices.

**Comment by rufilboy** [comment]
Thanks chief, will you like to work on that?

**Comment by rufilboy** [comment]
I've worked on this!

**Comment by rufilboy** [comment]
No problem
